//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFerramentas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ferramenta
    {
        public int Id { get; set; }
        public string Matricula { get; set; }
        public string Diametro { get; set; }
        public int LoteId { get; set; }
    
        public virtual Lote Lote { get; set; }
    }
}
